file = open("example.txt", "w")
print(file.write("Hello yas"))
file = open("example.txt","r")
print(file.read())
file.close()
file=open("example2.txt","a")
file.write("hi helloe")
file=open("example2.txt","a")
file.write("\n im yas")
file = open("C:\Users\ytaj3\OneDrive\Pictures\Screenshots\Screenshot 2025-12-28 145126.png","rb")
data = file.read()
print(data)